import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Tabs, Text } from '@geist-ui/core'
import React, { useState } from 'react';


export default function Home() {
  return (
    <div className={styles.container}>
      <Tabs initialValue="1">
      <Tabs.Item label="the wedding" value="1"><Text h2>January 14, 2023</Text><br /> <Text font="1.5rem" marginTop={"-25px"} marginBottom={"0px"}>At 2:45pm</Text><br /> <Text font="1rem" marginTop={"0px"} marginBottom={"0px"}>La Lomita Ranch<br /> 1985 La Lomita Way<br />  San Luis Obispo, California 93401</Text></Tabs.Item>
        <Tabs.Item label="holden" value="2">Holden is the groom.</Tabs.Item>
        <Tabs.Item label="alexia" value="3">Alexia is the bride.</Tabs.Item>
        <Tabs.Item label="philippe" value="4">Philippe is the dog.</Tabs.Item>
      </Tabs>
      <Head>
        <title>Holden + Alexia Wedding</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Holden & Alexia are getting married!
        </h1>

        <div className={styles.grid}>
            <h2>Information &rarr;</h2>
            <p className={styles.description}> &nbsp;Text me.</p>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
